from __future__ import annotations

from .api_surface import ApiSurfaceSpec

COLMAP_COMMANDS = (
    "automatic_reconstructor",
    "bundle_adjuster",
    "color_extractor",
    "database_cleaner",
    "database_creator",
    "database_merger",
    "delaunay_mesher",
    "exhaustive_matcher",
    "feature_extractor",
    "feature_importer",
    "geometric_verifier",
    "global_mapper",
    "guided_geometric_verifier",
    "help",
    "version",
    "hierarchical_mapper",
    "image_deleter",
    "image_filterer",
    "image_rectifier",
    "image_registrator",
    "image_undistorter",
    "image_undistorter_standalone",
    "mapper",
    "matches_importer",
    "mesh_simplifier",
    "mesh_texturer",
    "model_aligner",
    "model_analyzer",
    "model_clusterer",
    "model_comparer",
    "model_converter",
    "model_cropper",
    "model_merger",
    "model_orientation_aligner",
    "model_splitter",
    "model_transformer",
    "patch_match_stereo",
    "point_filtering",
    "point_triangulator",
    "pose_prior_mapper",
    "poisson_mesher",
    "project_generator",
    "rig_configurator",
    "rotation_averager",
    "sequential_matcher",
    "spatial_matcher",
    "stereo_fusion",
    "transitive_matcher",
    "view_graph_calibrator",
    "vocab_tree_builder",
    "vocab_tree_matcher",
    "vocab_tree_retriever",
)

COLMAP_LEGACY_COMMANDS = (
    *(
        command
        for command in COLMAP_COMMANDS
        if command
        not in {
            "global_mapper",
            "guided_geometric_verifier",
            "version",
            "mesh_simplifier",
            "mesh_texturer",
            "model_clusterer",
            "rotation_averager",
            "view_graph_calibrator",
        }
    ),
    "rig_bundle_adjuster",
)

HLOC_EXPECTED_ACTIONS = frozenset(
    {
        "hloc.convertModel",
        "hloc.extractFeatures",
        "hloc.listConfigs",
        "hloc.localizeSfm",
        "hloc.matchDense",
        "hloc.matchFeatures",
        "hloc.pairsCovisibility",
        "hloc.pairsExhaustive",
        "hloc.pairsPoses",
        "hloc.pairsRetrieval",
        "hloc.reconstruct",
        "hloc.runModule",
        "hloc.runPipeline",
        "hloc.triangulate",
    }
)

HLOC_FORBIDDEN_ACTIONS = frozenset(
    {
        "hloc.localizeInLoc",
        "hloc.colmapFromNvm",
        "hloc.pipelineAachen",
        "hloc.pipelineAachenV11",
        "hloc.pipelineAachenV11LoFTR",
        "hloc.pipelineRobotCar",
        "hloc.pipelineRobotCarColmapFromNvm",
        "hloc.pipelineCMU",
        "hloc.pipelineCambridge",
        "hloc.pipelineSevenScenes",
        "hloc.pipelineSevenScenesCorrectDepth",
        "hloc.pipelineFourSeasonsPrepareReference",
        "hloc.pipelineFourSeasonsLocalize",
    }
)

INSTANTSFM_EXPECTED_ACTIONS = frozenset(
    {
        "instantsfm.extractFeatures",
        "instantsfm.runGlobalSfm",
        "instantsfm.runModule",
        "instantsfm.runPipeline",
        "instantsfm.trainGaussianSplatting",
        "instantsfm.visualizeReconstruction",
    }
)

SPHERESFM_COMMANDS = (
    "help",
    "automatic_reconstructor",
    "bundle_adjuster",
    "color_extractor",
    "database_cleaner",
    "database_creator",
    "database_merger",
    "delaunay_mesher",
    "exhaustive_matcher",
    "feature_extractor",
    "feature_importer",
    "hierarchical_mapper",
    "image_deleter",
    "image_filterer",
    "image_rectifier",
    "image_registrator",
    "image_undistorter",
    "image_undistorter_standalone",
    "mapper",
    "matches_importer",
    "model_aligner",
    "model_analyzer",
    "model_comparer",
    "model_converter",
    "model_cropper",
    "model_merger",
    "model_orientation_aligner",
    "model_splitter",
    "model_transformer",
    "patch_match_stereo",
    "point_filtering",
    "point_triangulator",
    "poisson_mesher",
    "project_generator",
    "rig_bundle_adjuster",
    "sequential_matcher",
    "spatial_matcher",
    "sphere_cubic_reprojecer",
    "stereo_fusion",
    "transitive_matcher",
    "vocab_tree_builder",
    "vocab_tree_matcher",
    "vocab_tree_retriever",
)

REALITYSCAN_COMMANDS = (
    "newScene",
    "load",
    "save",
    "start",
    "unlockPPIProject",
    "add",
    "addFolder",
    "importVideo",
    "importHDRimages",
    "addImageWithCalibration",
    "importImageSelection",
    "selectImage",
    "selectAllImages",
    "deselectAllImages",
    "invertImageSelection",
    "execRSCMD",
    "quit",
    "setFeatureSource",
    "enableAlignment",
    "enableMeshing",
    "setDownscaleForDepthMaps",
    "enableInComponent",
    "setCalibrationGroupByExif",
    "setConstantCalibrationGroups",
    "lockPoseForContinue",
    "setPriorCalibrationGroup",
    "setPriorLensGroup",
    "editInputSelection",
    "align",
    "draft",
    "update",
    "detectFeatures",
    "mergeComponents",
    "exportXMP",
    "exportXMPForSelectedComponent",
    "importComponent",
    "importBundler",
    "importColmap",
    "exportLatestComponents",
    "setMinComponentSize",
    "exportSelectedComponentDir",
    "exportSelectedComponentFile",
    "exportRegistration",
    "exportUndistortedImages",
    "exportSTMap",
    "exportSparsePointCloud",
    "selectComponent",
    "selectMaximalComponent",
    "selectComponentWithLeastReprojectionError",
    "importGroundControlPoints",
    "importControlPointsMeasurements",
    "listControlPoints",
    "selectControlPoint",
    "invertControlPointSelection",
    "selectMeasurementByError",
    "selectMeasurementByIndex",
    "exportGroundControlPoints",
    "exportControlPointsMeasurements",
    "defineDistance",
    "detectMarkers",
    "setCamerasGravityDirection",
    "resetGround",
    "setGroundPlaneFromReconstructionRegion",
    "setReconstructionRegionAuto",
    "setReconstructionRegion",
    "setReconstructionRegionOnCPs",
    "setReconstructionRegionByDensity",
    "scaleReconstructionRegion",
    "moveReconstructionRegion",
    "rotateReconstructionRegion",
    "offsetReconstructionRegion",
    "exportReconstructionRegion",
    "calculatePreviewModel",
    "calculateNormalModel",
    "calculateHighModel",
    "continueModelCalculation",
    "selectModel",
    "selectLargestModelComponent",
    "exportModel",
    "exportSelectedModel",
    "exportModelToZip",
    "importModel",
    "set",
    "preset",
    "reset",
    "writeProgress",
    "printProgress",
    "stdConsole",
    "disableOnlineCommunication",
    "importGlobalSettings",
    "exportGlobalSettings",
    "setProjectCoordinateSystem",
    "setOutputCoordinateSystem",
)


def _prefixed(prefix: str, values: tuple[str, ...]) -> frozenset[str]:
    return frozenset(f"{prefix}{value}" for value in values)


PRESETS: dict[str, ApiSurfaceSpec] = {
    "generic": ApiSurfaceSpec(name="generic"),
    "colmap": ApiSurfaceSpec(
        name="colmap",
        expected_actions=_prefixed("colmap.", COLMAP_COMMANDS),
        forbidden_prefixes=("colmap.benchmark.",),
    ),
    "colmap-legacy": ApiSurfaceSpec(
        name="colmap-legacy",
        expected_actions=_prefixed("colmap.", COLMAP_LEGACY_COMMANDS),
        forbidden_prefixes=("colmap.benchmark.",),
    ),
    "hloc": ApiSurfaceSpec(
        name="hloc",
        expected_actions=HLOC_EXPECTED_ACTIONS,
        forbidden_actions=HLOC_FORBIDDEN_ACTIONS,
        forbidden_prefixes=("hloc.pipeline",),
    ),
    "instantsfm": ApiSurfaceSpec(
        name="instantsfm",
        expected_actions=INSTANTSFM_EXPECTED_ACTIONS,
        forbidden_prefixes=("instantsfm.benchmark.",),
    ),
    "realityscan": ApiSurfaceSpec(
        name="realityscan",
        expected_actions=_prefixed("realityscan.", REALITYSCAN_COMMANDS)
        | frozenset({"realityscan.reconstructImageFolder", "realityscan.runSequence"}),
        forbidden_prefixes=("realityscan.benchmark.",),
    ),
    "spheresfm": ApiSurfaceSpec(
        name="spheresfm",
        expected_actions=_prefixed("spheresfm.colmap.", SPHERESFM_COMMANDS)
        | frozenset({"spheresfm.convertToCubemap", "spheresfm.reconstructPanoramaFolder"}),
        forbidden_prefixes=("spheresfm.benchmark.",),
    ),
}
